---
title: "Creating test data"
author: "Ellie Harris"
output: html_document
---
# Creating your own test data

To test out code on what would be a small dataset, you can simply enter
test data yourself, e.g.

```{r, echo=TRUE}

df1 <- data.frame(ID = c(1, 2, 3, 4, 5),
                  var1 = c('a', 'b', 'c', 'd', 'e'),
                  var2 = c(1, 1, 0, 0, 1))

df1 
```

You can generate numbers, characters and more with functions.

```{r, echo=TRUE}
seq(1, 16, by=2) # sequence of numbers from 1 to 16 increment by 2.
LETTERS[1:8] # the 8 upper-case letters of the english alphabet.
month.abb[1:8] # the three-letter abbreviations for the first 8 English months
sample(10:20, 8, replace = TRUE) # 8 random numbers with replacement from 10 to 20.
letters[1:8] # the first 8 lower-case letters of the english alphabet.

df2 <- data.frame(a = seq(1,16,by=2), 
                  b = LETTERS[1:8],
                  x = month.abb[1:8],
                  y = sample(10:20,8, replace = TRUE),
                  z = letters[1:8])

df2

```

Similarly, you can sample from a given set of numbers with or without
replacement

```{r, echo=TRUE}
# Generate 15 numbers randomly sampled, with replacement, from the numbers 1, 2, 3
df3 = data.frame(X = sample(1:3, 15, replace = TRUE))

df3
```

You can also generate numbers using mean and standard deviations of
sampled data, eg. using rnorm

```{r, echo=TRUE}
set.seed(1) # allows random generations to be replicated
df4 <- data.frame(Y = rnorm(15), Z = ceiling(rnorm(15)))

df4
```
